#!/bin/bash
# Quick Commands Reference for IoT Monitoring System

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         IoT Environmental Monitoring - Quick Commands        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "🌤️  API MODE (Live Weather Data) - RECOMMENDED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Setup:          ./setup_api.sh"
echo "Start:          python3 main_api.py"
echo "Dashboard:      streamlit run streamlit_dashboard.py"
echo "Config:         nano config.json"
echo "View state:     cat current_state.json"
echo ""

echo "📄 CSV MODE (Simulated Data) - For Testing"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Setup:          ./setup_and_run.sh"
echo "Start:          python3 main_csv.py"
echo "Dashboard:      streamlit run streamlit_dashboard.py"
echo "Reset CSV:      echo \"0\" > row_tracker.txt"
echo "View row:       cat row_tracker.txt"
echo ""

echo "🛠️  SYSTEM CONTROL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Stop:           Ctrl + C (in terminal)"
echo "Kill all:       pkill -f main_api && pkill -f streamlit"
echo "Check running:  ps aux | grep -E 'main_|streamlit'"
echo ""

echo "📊 MONITORING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Live logs:      tail -f current_state.json"
echo "Check config:   cat config.json | grep -A 5 weather_api"
echo "Test API key:   curl \"http://api.openweathermap.org/data/2.5/weather?q=London&appid=YOUR_KEY\""
echo ""

echo "📝 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "API mode guide: cat README_API.md"
echo "CSV mode guide: cat README.md"
echo "Quick ref:      cat QUICK_REFERENCE.md"
echo "Testing steps:  cat TESTING_GUIDE.md"
echo "What changed:   cat UPGRADE_SUMMARY.md"
echo ""

echo "🔧 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "API not working:"
echo "  1. Wait 15 min after creating API key"
echo "  2. Check: cat config.json | grep api_key"
echo "  3. Test: curl \"http://api.openweathermap.org/data/2.5/weather?q=Bangalore&appid=YOUR_KEY\""
echo ""
echo "Dashboard not updating:"
echo "  1. Check main_api.py is running: ps aux | grep main_api"
echo "  2. Check state file: cat current_state.json"
echo "  3. Restart both terminals"
echo ""

echo "🌐 DASHBOARD URLS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Default:        http://localhost:8501"
echo "Alt port:       http://localhost:8505"
echo ""

echo "📦 DEPENDENCIES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Install:        pip install streamlit plotly requests"
echo "Check:          pip list | grep -E 'streamlit|plotly|requests'"
echo ""

echo "🎬 QUICK START FOR DEMO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Terminal 1:     python3 main_api.py"
echo "Terminal 2:     streamlit run streamlit_dashboard.py"
echo "Browser:        http://localhost:8501"
echo ""

echo "✨ Files Created in This Upgrade"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "api_weather_device.py      - Live weather sensor class"
echo "main_api.py                - API mode entry point"
echo "setup_api.sh               - API setup wizard"
echo "config.api.template.json   - Config template"
echo "README_API.md              - Complete API documentation"
echo "QUICK_REFERENCE.md         - Quick comparison guide"
echo "TESTING_GUIDE.md           - Step-by-step testing"
echo "UPGRADE_SUMMARY.md         - What changed"
echo "COMMANDS.sh                - This file"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Need help? Read: TESTING_GUIDE.md or README_API.md          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
